"""Sadržaj sajta. Sve cene, kontakti, ocene i recenzije su PROBNI podaci."""

ICONS = {
 "laptop": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="5" width="16" height="11" rx="1.5"/><path d="M2 19h20"/></svg>',
 "pc": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="12" rx="1.5"/><path d="M8 20h8M12 16v4"/></svg>',
 "drop": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3s6 6.5 6 11a6 6 0 0 1-12 0c0-4.5 6-11 6-11z"/></svg>',
 "screen": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="13" rx="1.5"/><path d="M7 8l4 4M14 9l3 3"/></svg>',
 "disk": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>',
 "fan": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="2"/><path d="M12 10c0-4 1-7 4-7 2 0 2 3 0 5M14 12c4 0 7 1 7 4 0 2-3 2-5 0M12 14c0 4-1 7-4 7-2 0-2-3 0-5M10 12c-4 0-7-1-7-4 0-2 3-2 5 0"/></svg>',
 "shield": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/><path d="M9 12l2 2 4-4"/></svg>',
 "bolt": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2L4 14h7l-1 8 9-12h-7z"/></svg>',
 "chip": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="6" width="12" height="12" rx="1.5"/><path d="M9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4"/></svg>',
}

# ---------- Podaci o uslugama (sve cene su probne) ----------
SERVICES = [
 dict(slug="popravka-laptopova", icon="laptop", title="Popravka laptopova",
  short="Ne pali se, ne puni, gasi se, ne prikazuje sliku. Kvarovi matične ploče, napajanja i šarki.",
  long="Laptop koji ne pali, ne puni bateriju ili se sam gasi najčešće ima kvar na napajanju ili matičnoj ploči. Prvo merimo napone i tražimo tačno koja komponenta ne radi, pa menjamo samo ono što je zaista neispravno.",
  symptoms=["Ne pali se ili se upali pa odmah ugasi","Ne puni bateriju ili punjač ne radi","Ventilator radi, ali nema slike","Šarke škripe, pucaju ili se kućište otvara","Sam se restartuje ili zaledi"],
  included=["Merenje napona i dijagnostika ploče","Zamena neispravne komponente","Provera baterije i punjača","Test od 2 sata pod opterećenjem","Garantni list na 6 meseci"],
  prices=[("Zamena baterije (sa delom)",3000,6000),("Zamena šarki",4000,7500),("Popravka napajanja na ploči",6000,12000),("Zamena matične ploče (sa delom)",12000,35000)],
  time="1–5 dana", related=["ciscenje-i-pasta","lemljenje-i-bga","ekrani-i-tastature"]),
 dict(slug="servis-racunara", icon="pc", title="Servis desktop računara",
  short="Dijagnostika kvarova, zamena napajanja, matične ploče i grafičke kartice, sklapanje po meri.",
  long="Kod desktop računara kvar je najčešće u napajanju, disku ili memoriji. Testiramo svaku komponentu posebno i predlažemo zamenu koja odgovara vašoj konfiguraciji i budžetu. Sklapamo i nove računare po meri, za kancelariju ili igranje.",
  symptoms=["Računar ne reaguje na dugme za paljenje","Pišti pri paljenju ili nema slike","Gasi se tokom igranja ili rada","Plavi ekran i česti restarti","Glasan rad i visoke temperature"],
  included=["Test napajanja, memorije i diska","Čišćenje kućišta i hladnjaka","Zamena komponente po vašem izboru","Ažuriranje BIOS-a i drajvera","Stres test procesora i grafike"],
  prices=[("Dijagnostika kvara",1500,3000),("Čišćenje kućišta i hladnjaka",2500,4000),("Sklapanje po meri (rad)",3000,5000),("Zamena napajanja (sa delom)",6000,14000)],
  time="1–3 dana", related=["nadogradnja","podaci-i-sistem","ciscenje-i-pasta"]),
 dict(slug="ciscenje-i-pasta", icon="fan", title="Čišćenje i termalna pasta",
  short="Laptop se greje, ventilator je glasan ili se računar gasi pri opterećenju.",
  long="Prašina u ventilatoru i osušena termalna pasta podižu temperaturu procesora i do 25 °C. Laptop tada usporava, bučan je i može da se gasi. Rastavljamo uređaj, čistimo ventilator i hladnjak i nanosimo kvalitetnu termalnu pastu.",
  symptoms=["Ventilator je stalno glasan","Kućište je vruće na dodir","Laptop usporava posle nekoliko minuta rada","Gasi se tokom igranja ili renderovanja","Poslednje čišćenje bilo je pre više od 2 godine"],
  included=["Kompletno rastavljanje uređaja","Čišćenje ventilatora i rebara hladnjaka","Nova termalna pasta (i termo podloge po potrebi)","Merenje temperature pre i posle","Podmazivanje ventilatora"],
  prices=[("Desktop računar",2500,4000),("Standardni laptop",3500,4500),("MacBook",4500,6000),("Gejming laptop",5500,7500)],
  time="24 h", related=["popravka-laptopova","nadogradnja","servis-racunara"],
  ba=("Temperatura procesora pod opterećenjem", "°C", 96, 71, 110)),
 dict(slug="ekrani-i-tastature", icon="screen", title="Ekrani i tastature",
  short="Zamena ekrana, tastature, touchpada, kućišta i šarki.",
  long="Napukao ekran, linije na slici, tamna slika ili tasteri koji ne rade rešavaju se zamenom dela. Proveravamo tačan model panela ili tastature, poručujemo odgovarajući deo i ugrađujemo ga, najčešće za jedan do tri dana.",
  symptoms=["Napukao ili razbijen ekran","Linije, fleke ili treperenje slike","Slika je jedva vidljiva (pozadinsko svetlo)","Pojedini tasteri ne rade","Touchpad ne reaguje"],
  included=["Provera tačnog modela dela","Nabavka novog panela ili tastature","Ugradnja i podešavanje","Provera kamere, mikrofona i Wi-Fi antena","Garancija 6 meseci na deo i rad"],
  prices=[("Zamena touchpada",4000,7000),("Zamena tastature",4900,9000),("Ekran HD (sa delom)",9900,13000),("Ekran Full HD IPS (sa delom)",12000,18000)],
  time="1–3 dana", related=["popravka-laptopova","prosuta-tecnost","lemljenje-i-bga"]),
 dict(slug="podaci-i-sistem", icon="disk", title="Podaci i sistem",
  short="Instalacija Windows-a, uklanjanje virusa, prebacivanje i spasavanje podataka.",
  long="Spor sistem, virusi ili disk koji otkazuje ne moraju da znače gubitak fajlova. Pravimo kopiju vaših podataka, čistimo ili ponovo instaliramo sistem i vraćamo fajlove tamo gde su bili. Ako disk ne radi, pokušavamo da spasemo podatke.",
  symptoms=["Windows se sporo pokreće ili se ne pokreće","Iskaču reklame i nepoznati programi","Disk škripi ili se ne vidi","Slučajno obrisani fajlovi","Prelazak na novi računar"],
  included=["Rezervna kopija podataka pre rada","Instalacija i aktivacija sistema","Drajveri i osnovni programi","Vraćanje fajlova i podešavanja","Provera stanja diska"],
  prices=[("Prebacivanje podataka",1500,3000),("Uklanjanje virusa",2000,3500),("Instalacija Windows-a",2500,3500),("Spasavanje podataka sa oštećenog diska",5000,20000)],
  time="isti dan", related=["nadogradnja","servis-racunara","popravka-laptopova"]),
 dict(slug="nadogradnja", icon="chip", title="Nadogradnja",
  short="Ugradnja SSD diska i dodatne RAM memorije. Stari računar postaje primetno brži.",
  long="Najisplativija nadogradnja starijeg računara je SSD disk. Sistem se pokreće nekoliko puta brže, a programi se otvaraju odmah. Prebacujemo ceo sistem sa starog diska, tako da sve ostaje kako je bilo, samo brže.",
  symptoms=["Sistem se pokreće duže od jednog minuta","Programi se dugo otvaraju","Računar koči kad je otvoreno više kartica","Pun disk i stalna upozorenja","Računar je stariji od 4 godine"],
  included=["Savet koji deo odgovara vašem uređaju","Kloniranje sistema na novi disk","Ugradnja SSD-a i RAM memorije","Provera brzine pre i posle","Stari disk vraćamo vama"],
  prices=[("Kloniranje sistema",1500,2500),("Ugradnja SSD-a (samo rad)",2000,2500),("RAM 8 GB sa ugradnjom",4500,6500),("SSD 500 GB sa ugradnjom",6500,9000)],
  time="isti dan", related=["podaci-i-sistem","ciscenje-i-pasta","servis-racunara"],
  ba=("Vreme pokretanja sistema", "s", 58, 12, 70)),
 dict(slug="prosuta-tecnost", icon="drop", title="Prosuta tečnost",
  short="Hitno čišćenje matične ploče od korozije i procena oštećenja.",
  long="Voda, kafa ili sok na tastaturi izazivaju koroziju koja se širi danima. Što pre donesete laptop, veća je šansa da se popravi jeftino. Rastavljamo ga, čistimo ploču u ultrazvučnoj kadi i menjamo samo oštećene delove.",
  symptoms=["Prosuta voda, kafa, čaj ili sok","Tasteri lepe ili ne rade","Laptop se ugasio odmah posle prosipanja","Pali se, ali se čudno ponaša","Zelene ili bele naslage u portovima"],
  included=["Hitno rastavljanje istog dana","Čišćenje ploče u ultrazvučnoj kadi","Sušenje i provera svih napona","Zamena oštećenih komponenti","Pismena procena pre popravke"],
  prices=[("Čišćenje ploče ultrazvukom",4500,6500),("Zamena tastature posle prosipanja",5000,9000),("Popravka oštećenih komponenti",6000,15000)],
  time="2–5 dana", related=["ekrani-i-tastature","lemljenje-i-bga","popravka-laptopova"],
  tip=["Odmah isključite laptop i izvucite punjač.","Ne pokušavajte da ga upalite da proverite da li radi.","Okrenite ga naopako, otvorenog ekrana, da tečnost iscuri.","Ne sušite ga fenom. Donesite ga u servis što pre."]),
 dict(slug="lemljenje-i-bga", icon="bolt", title="Lemljenje i BGA",
  short="Zamena konektora za punjenje, čipova i komponenti na matičnoj ploči.",
  long="Polomljen konektor za punjenje ili neispravan čip ne znače kraj laptopa. Mikrolemljenjem menjamo pojedinačne komponente na matičnoj ploči, umesto da menjamo celu ploču, što je obično nekoliko puta jeftinije.",
  symptoms=["Punjač radi samo pod određenim uglom","USB ili HDMI port je polomljen","Laptop ne pali posle udara struje","Grafički čip pravi artefakte na slici","Servis je ponudio zamenu cele ploče"],
  included=["Pregled ploče pod mikroskopom","Zamena konektora i portova","Zamena SMD komponenti i čipova","BGA reballing na profesionalnoj stanici","Provera napona posle popravke"],
  prices=[("Zamena USB ili HDMI porta",5000,8000),("Zamena konektora za punjenje",6000,9000),("Reballing ili zamena čipa",12000,25000)],
  time="3–7 dana", related=["popravka-laptopova","prosuta-tecnost","servis-racunara"]),
 dict(slug="poslovni-korisnici", icon="shield", title="Poslovni korisnici",
  short="Održavanje računara za firme, prioritetni rokovi i mesečno fakturisanje.",
  long="Za kancelarije i male firme preuzimamo redovno održavanje računara i mreže. Dobijate prioritet u servisu, dolazak na lokaciju u Beogradu i jedan mesečni račun umesto pojedinačnih popravki.",
  symptoms=["Imate 3 ili više računara u kancelariji","Zastoji u radu vas koštaju","Nemate svog IT stručnjaka","Potrebne su vam redovne rezervne kopije","Otvarate novu kancelariju"],
  included=["Prioritetni rok popravke","Dolazak na lokaciju u Beogradu","Redovno čišćenje i ažuriranje","Postavljanje novih radnih mesta","Mesečni izveštaj i jedna faktura"],
  prices=[("Intervencija na lokaciji",3000,5000),("Postavljanje nove radne stanice",3500,6000),("Mesečno održavanje do 10 računara",15000,25000)],
  time="po ugovoru", related=["servis-racunara","podaci-i-sistem","nadogradnja"]),
]
BY_SLUG = {s["slug"]: s for s in SERVICES}

# ---------- Faze postupka ----------
STEPS = [
 ("Prijava kvara","Prijava","Odmah","Pozovete nas, popunite formu na sajtu ili jednostavno donesete uređaj. Zakazivanje nije potrebno. Za firme i veće količine dolazimo po uređaje na adresu u Beogradu.",
   ["Telefon, Viber ili forma na sajtu","Bez zakazivanja"]),
 ("Prijem i radni nalog","Prijem","10 minuta","Zajedno pregledamo uređaj i zapišemo spoljašnje stanje, opis kvara i pribor koji ostavljate. Dobijate radni nalog sa brojem po kojem pratite status.",
   ["Zapisnik o stanju uređaja","Broj radnog naloga, npr. RN-2026-0417"]),
 ("Dijagnostika","Dijagnostika","Isti ili sledeći dan","Serviser rastavlja i testira uređaj da bi pronašao pravi uzrok kvara. Dijagnostika je besplatna ako popravku radite kod nas.",
   ["Merenje napona i temperatura","Test diska, memorije i ekrana"]),
 ("Procena i vaše odobrenje","Procena","Poziv ili SMS","Javljamo vam šta je neispravno, koliko košta popravka i koliko traje. Ništa ne radimo dok ne odobrite. Ako odustanete, uređaj preuzimate u istom stanju.",
   ["Tačna cena pre početka rada","Bez skrivenih troškova"]),
 ("Popravka","Popravka","Obično 24–72 h","Menjamo ili popravljamo neispravne delove. Ako deo treba poručiti, javljamo vam tačan rok isporuke.",
   ["Originalni ili provereni zamenski delovi","Antistatičko radno mesto"]),
 ("Testiranje","Test","Najmanje 2 sata","Svaki uređaj prolazi test pod opterećenjem: temperature, napajanje, ekran, tastatura, portovi, mreža i zvuk.",
   ["Stres test procesora i grafike","Provera svih portova"]),
 ("Preuzimanje i garancija","Preuzimanje","Kad vam odgovara","Pozivamo vas kad je uređaj spreman. Plaćate gotovinom ili karticom i dobijate fiskalni račun i garantni list na 6 meseci.",
   ["Fiskalni račun","Garancija 6 meseci"]),
]
STEPS = [(a,b,c,d,[x.replace("provereni","provereni") for x in e]) for a,b,c,d,e in STEPS]

faq = [
 ("Dijagnostika i cene", [
   ("Koliko košta dijagnostika?","Dijagnostika je besplatna ako popravku radite kod nas. Ako odustanete od popravke, naplaćujemo 1.500 RSD <span class=\"probno\">probno</span>."),
   ("Da li ću znati cenu pre popravke?","Da. Posle dijagnostike vas pozovemo i kažemo tačnu cenu i rok. Ništa ne radimo bez vašeg odobrenja."),
   ("Kako mogu da platim?","Gotovinom, platnim karticama ili uplatom na račun za pravna lica. Dobijate fiskalni račun."),
 ]),
 ("Rokovi i garancija", [
   ("Koliko traje popravka?","Čišćenje, instalacija sistema i ugradnja SSD-a obično su gotovi isti ili sledeći dan. Zamena ekrana i delova traje 1 do 3 dana, a složenije popravke matične ploče do 7 dana."),
   ("Koliko traje garancija?","Na rad i ugrađene delove dajemo 6 meseci garancije. Garancija ne važi za nova mehanička oštećenja i prosutu tečnost."),
   ("Da li postoji hitna popravka?","Da, za većinu usluga možemo da završimo posao isti dan uz doplatu od 30%, ako je deo na stanju."),
 ]),
 ("Podaci i uređaji", [
   ("Da li ću izgubiti podatke?","Kod većine popravki podaci ostaju netaknuti. Ako je potrebna reinstalacija ili zamena diska, pre toga vas pitamo i nudimo prebacivanje podataka."),
   ("Da li popravljate MacBook računare?","Da. Radimo čišćenje, zamenu baterije, tastature i SSD nadogradnju na modelima gde je to moguće."),
   ("Mogu li da pratim status popravke?","Da. Pozovite nas ili pošaljite broj radnog naloga, pa ćemo vam reći u kom je koraku popravka."),
   ("Šta ako se popravka ne isplati?","Iskreno vam kažemo ako je popravka skuplja od vrednosti uređaja. Možemo da spasemo podatke i predložimo zamenu."),
 ]),
]
